[tool.poetry]
name = "mlproject-studentperformance"
version = "0.1.0"
description = "end to end ml project"
authors = ["Luis Olcay <luis.olcay@uc.cl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
